# Predicting 1993 bombings/explosions by taking the mean of 1990-1992 and 1994-1996 bombings/explosions Worldwide.

In [3]:
import pandas as pd
xls_file = pd.ExcelFile('globalterrorismdb_0616dist.xlsx')
xls_file

In [4]:
xls_file.sheet_names

[u'Data']

In [5]:
dfwhole = xls_file.parse('Data')
dfwhole.head(2)

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
0,197000000001,1970,0,0,NaN,0,NaN,58,Dominican Republic,2,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
1,197000000002,1970,0,0,NaN,0,NaN,130,Mexico,1,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN

In [13]:
dfwhole.groupby('iyear').attacktype1.value_counts().sum()

156772

In [64]:
dfwhole.groupby(['iyear', 'country_txt']).attacktype1.count()

iyear  country_txt
1970   Argentina                     21
       Australia                      1
       Belgium                        1
       Bolivia                        1
       Brazil                         6
       Canada                         2
       Colombia                       1
       Dominican Republic             2
       East Germany (GDR)            12
       Egypt                          1
       Ethiopia                       3
       Greece                         3
       Guatemala                      4
       Iran                           5
       Ireland                        1
       Israel                         1
       Italy                          3
       Japan                          2
       Jordan                         9
       Lebanon                        1
       Mexico                         2
       Netherlands                    2
       Nicaragua                      1
       Pakistan                       1
       Paraguay                       1
       Philippines                   10
       Spain                          4
       Switzerland                    3
       Turkey                        12
       United Kingdom                12
                                   ...
2015   Pakistan                    1235
       Paraguay                      19
       Peru                          10
       Philippines                  717
       Qatar                          1
       Russia                        21
       Saudi Arabia                 103
       Senegal                        2
       Somalia                      407
       South Africa                   2
       South Korea                    1
       South Sudan                   54
       Sri Lanka                     11
       Sudan                        158
       Sweden                        36
       Syria                        485
       Tajikistan                     3
       Tanzania                      14
       Thailand                     277
       Trinidad and Tobago            1
       Tunisia                       17
       Turkey                       416
       Uganda                        10
       Ukraine                      637
       United Kingdom               115
       United States                 38
       Uzbekistan                     1
       Venezuela                      3
       West Bank and Gaza Strip     247
       Yemen                        668
Name: attacktype1, dtype: int64

In [8]:
dfwhole[(dfwhole.attacktype1 == 3)]

,eventid,iyear,imonth,iday,approxdate,extended,resolution,country,country_txt,region,...,addnotes,scite1,scite2,scite3,dbsource,INT_LOG,INT_IDEO,INT_MISC,INT_ANY,related
3,197001000002,1970,1,0,NaN,0,NaN,78,Greece,8,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
7,197001020002,1970,1,2,NaN,0,NaN,217,United States,1,...,"Damages were estimated to be between $20,000-$...",Committee on Government Operations United Stat...,"Christopher Hewitt, ""Political Violence and Te...",NaN,Hewitt Project,-9,-9,0,-9,NaN
10,197001050001,1970,1,1,NaN,0,NaN,217,United States,1,...,NaN,NaN,NaN,NaN,PGIS,0,0,0,0,NaN
15,197001100001,1970,1,10,NaN,0,NaN,499,East Germany (GDR),9,...,NaN,NaN,NaN,NaN,PGIS,0,1,1,1,NaN
17,197001120001,1970,1,12,NaN,0,NaN,217,United States,1,...,"One half hour after the bomb explosion, an ano...","""Blast Damages Flatbush School,"" New York Time...","Linda Greenhouse, ""Madison School Puzzled By B...",Committee on Government Operations United Stat...,Hewitt Project,-9,-9,0,-9,NaN
18,197001120002,1970,1,12,NaN,0,NaN,217,United States,1,...,NaN,Committee on the Judiciary United States Sena...,"""Toward People's War for Independence and Soci...",NaN,Hewitt Project,-9,-9,0,-9,NaN
22,197001190002,1970,1,19,NaN,0,NaN,217,United States,1,...,Witnesses observed three African American male...,Committee on Government Operations United Stat...,"Christopher Hewitt, ""Political Violence and Te...","Seattle University, ""1965-1975: Troubled Times...",Hewitt Project,-9,-9,0,-9,NaN
23,197001190003,1970,1,19,NaN,0,NaN,217,United States,1,...,Judith and Silas Bissell were both members of ...,Committee on Government Operations United Stat...,"Christopher Hewitt, ""Political Violence and Te...","Earl Caldwell, ""Fear Grows In Seattle As Polic...",Hewitt Project,-9,-9,0,-9,NaN
26,197001210001,1970,1,21,NaN,0,NaN,160,Philippines,5,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,1,1,NaN
28,197001220002,1970,1,22,NaN,0,NaN,217,United States,1,...,This attack might be linked with other episode...,Committee on Government Operations United Stat...,"""Beef Plant Workers in Nebraska Await Call to ...",NaN,Hewitt Project,-9,-9,0,-9,NaN
31,197001260001,1970,1,26,NaN,0,NaN,217,United States,1,...,"Police, at the time, suspected that this attac...","""Miss. City Is Desegregation Trouble Spot,"" Ch...","""Black, White Killings in South, West Trigger ...","Christopher Hewitt, ""Political Violence and Te...",Hewitt Project,-9,-9,0,-9,NaN
35,197001280002,1970,1,28,NaN,0,NaN,217,United States,1,...,NaN,Committee on Government Operations United Stat...,"""Synagogue Blasted,"" Tri City Herald, January ...",NaN,Hewitt Project,-9,-9,0,-9,NaN
36,197001300001,1970,1,30,NaN,0,NaN,217,United States,1,...,This incident might be part of a multiple atta...,Committee on Government Operations United Stat...,"""Beef Plant Workers in Nebraska Await Call to ...",NaN,Hewitt Project,-9,-9,0,-9,197001300002
37,197001300002,1970,1,30,NaN,0,NaN,217,United States,1,...,This incident might be part of a multiple atta...,Committee on Government Operations United Stat...,"""Beef Plant Workers in Nebraska Await Call to ...",NaN,Hewitt Project,-9,-9,0,-9,197001300001
40,197001310002,1970,1,31,NaN,0,NaN,217,United States,1,...,NaN,Committee on Government Operations United Stat...,"Christopher Hewitt, ""Political Violence and Te...",NaN,Hewitt Project,-9,-9,0,-9,NaN
46,197002040001,1970,2,4,NaN,0,NaN,217,United States,1,...,This attack might be linked with other episode...,Committee on Government Operations United Stat...,NaN,NaN,Hewitt Project,-9,-9,0,-9,NaN
47,197002060001,1970,2,6,NaN,0,NaN,217,United States,1,...,School buses played a significant role in tran...,"Anthony Ripley, ""Denver Blasts Destroy 24 Scho...","Marcia McKnight Trick, ""Chronology of Incident...",NaN,Hewitt Project,-9,-9,0,-9,NaN
48,197002060002,1970,2,6,NaN,0,NaN,217,United States,1,...,The general consensus among sources is that t...,"Earl Caldwell, ""Fear Grows in Seattle as Polic...","Steven V. Roberts, ""Bombings on Rise Over the ...",Committee on Government Operations United Stat...,Hewitt Project,-9,-9,0,-9,NaN
49,197002060003,1970,2,6,NaN,0,NaN,217,United States,1,...,This might be linked with 197001280002. Both ...,Committee on Government Operations United Stat...,NaN,NaN,Hewitt Project,-9,-9,0,-9,NaN
55,197002080001,1970,2,8,NaN,0,NaN,217,United States,1,...,Part of a multiple attack with 197002080002 an...,"""2 Bombs Explode at G.E. Buildings,"" New York ...","""Puerto Rican Group Describes Bombings,"" New Y...","William Sater, ""Puerto Rican Terrorists: A Pos...",Hewitt Project,0,1,0,1,"197002080002, 197002090003"
56,197002080002,1970,2,8,NaN,0,NaN,217,United States,1,...,Part of a multiple attack with 197002080001 an...,"""2 Bombs Explode at G.E. Buildings,"" New York ...","""Puerto Rican Group Describes Bombings,"" New Y...","William Sater, ""Puerto Rican Terrorists: A Pos...",Hewitt Project,0,1,0,1,"197002080001, 197002090003"
57,197002090003,1970,2,9,NaN,0,NaN,217,United States,1,...,Part of a multiple attack with 197002080001 an...,"""2 Bombs Explode at G.E. Buildings,"" New York ...","""Puerto Rican Group Describes Bombings,"" New Y...","""Bomb Case Figure Found Guilty Here,"" New York...",Hewitt Project,0,1,0,1,"197002080001, 197002080002"
58,197002090004,1970,2,9,NaN,0,NaN,217,United States,1,...,This was one of many attacks against General E...,"""New York GE Offices Damaged by 2 Bombs,"" The ...","""GE Empolye's Cars Blown Up by Dynamite,"" Hart...",NaN,Hewitt Project,-9,-9,0,-9,NaN
61,197002130001,1970,2,13,NaN,0,NaN,217,United States,1,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,0,-9,NaN
63,197002130003,1970,2,13,NaN,0,NaN,217,United States,1,...,The bombs detonated 30 seconds apart. The bom...,Committee on Government Operations United Stat...,"""Bombs Injure 2 Policemen in Berkeley,"" Washin...","""San Francisco Bomb Injured 7 Policemen,"" Wash...",Hewitt Project,-9,-9,0,-9,NaN
64,197002150001,1970,2,15,NaN,0,NaN,217,United States,1,...,This was one of many bank bombings in New York...,"""Door of Chase Bank Is Damaged By Bomb,"" New Y...","""Bank Blasted,"" The Montreal Gazette, July 16,...","Marcia McKnight Trick, ""Chronology of Incident...",Hewitt Project,-9,-9,0,-9,NaN
66,197002160001,1970,2,16,NaN,0,NaN,217,United States,1,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,0,-9,197002160004
67,197002160002,1970,2,16,NaN,0,NaN,217,United States,1,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,0,-9,197002160003
68,197002160003,1970,2,16,NaN,0,NaN,217,United States,1,...,NaN,NaN,NaN,NaN,PGIS,-9,-9,0,-9,197002160002
70,197002170001,1970,2,17,NaN,0,NaN,217,United States,1,...,The dynamite was found a day after 19700216000...,Committee on Government Operations United Stat...,"""San Francisco Bomb Injured 7 Policemen,"" Wash...","Marcia McKnight Trick, ""Chronology of Incident...",Hewitt Project,-9,-9,0,-9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156728,201512300020,2015,12,30,NaN,0,NaN,95,Iraq,10,...,NaN,"""Iraqi joint forces repel ISIS attack, kill 12...","""State PAO: Iraqi Media Summary for 30 Decembe...","""Iraqi joint forces repel Daesh attack,"" Islam...",START Primary Collection,-9,-9,0,-9,NaN
156730,201512300023,2015,12,30,2015-12-30 00:00:00,0,NaN,4,Afghanistan,6,...,NaN,"""Afghanistan: Afghan Police Claim Foiling Four...",NaN,NaN,START Primary Collection,-9,-9,1,1,NaN
156731,201512300024,2015,12,30,2015-12-30 00:00:00,0,NaN,4,Afghanistan,6,...,NaN,"""Afghanistan: Afghan Police Claim Foiling Four...",NaN,NaN,START Primary Collection,-9,-9,1,1,NaN
156732,201512300025,2015,12,30,NaN,0,NaN,19,Bangladesh,6,...,Casualty numbers for this attack represent a d...,"""Bomb blast in Narsingdi polling centres,"" Fin...",NaN,NaN,START Primary Collection,-9,-9,0,-9,"201512300025, 201512300026, 201512300027"
156733,201512300026,2015,12,30,NaN,0,NaN,19,Bangladesh,6,...,Casualty numbers for this attack represent a d...,"""Bomb blast in Narsingdi polling centres,"" Fin...",NaN,NaN,START Primary Collection,-9,-9,0,-9,"201512300025, 201512300026, 201512300027"
156734,201512300027,2015,12,30,NaN,0,NaN,19,Bangladesh,6,...,Casualty numbers for this attack represent a d...,"""Bomb blast in Narsingdi polling centres,"" Fin...",NaN,NaN,START Primary Collection,-9,-9,0,-9,"201512300025, 201512300026, 201512300027"
156735,201512300034,2015,12,30,NaN,0,NaN,60,Egypt,10,...,NaN,"""Security detonates IED outside Giza checkpoin...","""BBC Monitoring: Terrorism Digest 30-31 Decemb...",NaN,START Primary Collection,0,0,0,0,NaN
156736,201512300036,2015,12,30,2015-12-30 00:00:00,0,NaN,4,Afghanistan,6,...,NaN,"""Afghan army defuses 17 improvised bombs in so...",NaN,NaN,START Primary Collection,-9,-9,1,1,NaN
156737,201512300037,2015,12,30,2015-12-30 00:00:00,0,NaN,4,Afghanistan,6,...,NaN,"""Afghan army defuses 17 improvised bombs in so...",NaN,NaN,START Primary Collection,-9,-9,1,1,NaN
156740,201512300044,2015,12,30,NaN,0,NaN,108,Laos,5,...,NaN,"""BOMB EXPLOSION KILLS TWO CHINESE IN LAOS,"" St...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
156741,201512310001,2015,12,31,2015-12-31 00:00:00,0,NaN,95,Iraq,10,...,NaN,"""Iraq: Roundup of Security Incidents 29 Decemb...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
156742,201512310002,2015,12,31,NaN,0,NaN,95,Iraq,10,...,NaN,"""Iraq: Roundup of Security Incidents 29 Decemb...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
156743,201512310004,2015,12,31,NaN,0,NaN,95,Iraq,10,...,NaN,"""Iraq: Roundup of Security Incidents 29 Decemb...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
156744,201512310005,2015,12,31,NaN,0,NaN,95,Iraq,10,...,NaN,"""8 people killed, wounded in bomb south west o...","""Iraq: Roundup of Security Incidents 29 Decemb...","""Terrorism: Transcript of ISIL's Al-Bayan Radi...",START Primary Collection,-9,-9,0,-9,NaN
156745,201512310006,2015,12,31,NaN,0,NaN,95,Iraq,10,...,NaN,"""7 people killed, wounded in bomb blast east o...","""Iraq: Security Roundup 1900 GMT 31 December 2...",NaN,START Primary Collection,-9,-9,0,-9,NaN
156749,201512310012,2015,12,31,NaN,0,NaN,228,Yemen,10,...,NaN,"""Yemen: Security Roundup 2000 GMT 31 December ...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
156750,201512310013,2015,12,31,NaN,0,NaN,173,Saudi Arabia,10,...,NaN,"""Saudi-led coalition ending Yemen ceasefire, s...","""Yemen: Security Roundup 2000 GMT 31 December ...",NaN,START Primary Collection,1,1,0,1,NaN
156751,201512310015,2015,12,31,NaN,0,NaN,60,Egypt,10,...,There is doubt that this incident meets terror...,"""Egypt parents, 3 children killed by shelling ...","""Egypt parents, three children killed by shell...","""Egypt officials: Militants in Sinai kill enti...",START Primary Collection,-9,-9,0,-9,NaN
156752,201512310016,2015,12,31,NaN,0,NaN,173,Saudi Arabia,10,...,NaN,"""Missile from Yemen kills 3 Saudi civilians,"" ...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
156754,201512310018,2015,12,31,NaN,0,NaN,209,Turkey,10,...,NaN,"""Anadolu Agency Reports One PKK Member Killed,...",NaN,NaN,START Primary Collection,0,0,0,0,NaN
156755,201512310019,2015,12,31,NaN,0,NaN,214,Ukraine,9,...,NaN,"""Ukrainian Police Blame Second Crimean Power O...","""Ukrainian police say Crimean power line damag...","""Power transmission line tower in Kherson regi...",START Primary Collection,-9,-9,0,-9,NaN
156756,201512310020,2015,12,31,NaN,0,NaN,92,India,6,...,NaN,"""Grenade hurled at Police Station Khanyar,"" Ka...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN
156758,201512310022,2015,12,31,NaN,0,NaN,65,Ethiopia,11,...,Casualty numbers for this incident conflict ac...,"""Students said leaving southern Ethiopian univ...","""Hand grenade attack kills 2 at Ethiopian univ...","""Hand grenade attack kills two at Ethiopian un...",START Primary Collection,-9,-9,0,-9,NaN
156759,201512310024,2015,12,31,NaN,0,NaN,160,Philippines,5,...,NaN,"""Philippines: BIFF launches simultaneous attac...","""BIFF harassments, rido disrupt New Year celeb...","""HeadlinesTroops beat back BIFF assaults on 3 ...",START Primary Collection,0,0,0,0,"201512310024, 201512310026, 201512310027"
156763,201512310028,2015,12,31,2015-12-31 00:00:00,0,NaN,95,Iraq,10,...,NaN,"""Bomb blast kills soldier, wounds another in s...","""2 soliders killed, wounded in explosion in so...",NaN,START Primary Collection,-9,-9,0,-9,NaN
156764,201512310029,2015,12,31,NaN,0,NaN,153,Pakistan,6,...,NaN,"""Unknown armed men fire 3 rockets in Mand and ...","""Highlights: Pakistan Balochistan Press 1 Janu...",NaN,START Primary Collection,-9,-9,0,-9,NaN
156765,201512310030,2015,12,31,NaN,0,NaN,153,Pakistan,6,...,NaN,"""Unknown armed men fire 3 rockets in Mand and ...","""Highlights: Pakistan Balochistan Press 1 Janu...",NaN,START Primary Collection,0,0,0,0,NaN
156766,201512310031,2015,12,31,NaN,0,NaN,153,Pakistan,6,...,NaN,"""Unknown armed men fire 3 rockets in Mand and ...","""Highlights: Pakistan Balochistan Press 1 Janu...",NaN,START Primary Collection,0,0,0,0,NaN
156767,201512310032,2015,12,31,NaN,0,NaN,34,Burundi,11,...,Casualty numbers for this incident conflict ac...,"""1 dead, dozens injured in Burundi grenade att...","""One dead, dozen hurt in Burundi grenade attac...",NaN,START Primary Collection,-9,-9,0,-9,NaN
156768,201512310033,2015,12,31,2015-12-31 00:00:00,0,NaN,96,Ireland,8,...,NaN,"""GardaÃ­ investigate Knocknaheeny pipe bomb,"" C...",NaN,NaN,START Primary Collection,-9,-9,0,-9,NaN

In [65]:
##creating boolean filters to pull the sum of bombings/explosions from 1991,1992,1994,1995

# df_prior = dfwhole[(dfwhole.attacktype1 == 3) & (dfwhole.region == 6) & (dfwhole.iyear <= 2000)].
# groupby(['iyear', 'country_txt']).attacktype1.count().values
dfwhole[(dfwhole.attacktype1 ==3) & 
        (dfwhole.iyear == 1990)].groupby(['iyear', 'region']).attacktype1.count().sum()

1731

In [66]:
dfwhole[(dfwhole.attacktype1 ==3) & 
        (dfwhole.iyear == 1991)].groupby(['iyear', 'region']).attacktype1.count().sum()

1988

In [58]:
dfwhole[(dfwhole.attacktype1 ==3) & 
        (dfwhole.iyear == 1992)].groupby(['iyear', 'region']).attacktype1.value_counts().sum()

1738

In [55]:
dfwhole[(dfwhole.attacktype1 ==3) & 
        (dfwhole.iyear == 1994)].groupby(['iyear', 'region']).attacktype1.value_counts().sum()

1153

In [56]:
dfwhole[(dfwhole.attacktype1 ==3) & 
        (dfwhole.iyear == 1995)].groupby(['iyear', 'region']).attacktype1.value_counts().sum()

791

In [57]:
dfwhole[(dfwhole.attacktype1 ==3) & 
        (dfwhole.iyear == 1996)].groupby(['iyear', 'region']).attacktype1.value_counts().sum()

1217

In [54]:
#Calculating the mean of the above 6 values from the 3 years before and after 1993
(1217+791+1153+1738+1988+1731)/6
# This appraoch gives us 1436 bombings/explosions took place in 1993.

1436

In [75]:
## Looking at the number of bombs/explosions by region. considering taking a look at mean of regions versus overall 
## as I did above.
dfwhole[(dfwhole.attacktype1 ==3) & 
        (dfwhole.iyear == 1990)].groupby(['region_txt']).attacktype1_txt.value_counts()

region_txt                   attacktype1_txt
Australasia & Oceania        Bombing/Explosion      1
Central America & Caribbean  Bombing/Explosion    172
East Asia                    Bombing/Explosion     27
Eastern Europe               Bombing/Explosion     27
Middle East & North Africa   Bombing/Explosion    137
North America                Bombing/Explosion     16
South America                Bombing/Explosion    500
South Asia                   Bombing/Explosion    179
Southeast Asia               Bombing/Explosion    157
Sub-Saharan Africa           Bombing/Explosion    287
Western Europe               Bombing/Explosion    228
Name: attacktype1_txt, dtype: int64

In [76]:
dfwhole[(dfwhole.attacktype1 ==3) & 
        (dfwhole.iyear == 1991)].groupby(['region_txt']).attacktype1_txt.value_counts()

region_txt                   attacktype1_txt
Australasia & Oceania        Bombing/Explosion      3
Central America & Caribbean  Bombing/Explosion    295
Central Asia                 Bombing/Explosion      2
East Asia                    Bombing/Explosion      6
Eastern Europe               Bombing/Explosion     38
Middle East & North Africa   Bombing/Explosion    268
North America                Bombing/Explosion     13
South America                Bombing/Explosion    687
South Asia                   Bombing/Explosion    208
Southeast Asia               Bombing/Explosion     81
Sub-Saharan Africa           Bombing/Explosion     46
Western Europe               Bombing/Explosion    341
Name: attacktype1_txt, dtype: int64

In [77]:
dfwhole[(dfwhole.attacktype1 ==3) & 
        (dfwhole.iyear == 1992)].groupby(['region_txt']).attacktype1_txt.value_counts()

region_txt                   attacktype1_txt
Central America & Caribbean  Bombing/Explosion     74
Central Asia                 Bombing/Explosion     24
East Asia                    Bombing/Explosion     22
Eastern Europe               Bombing/Explosion     40
Middle East & North Africa   Bombing/Explosion    253
North America                Bombing/Explosion      5
South America                Bombing/Explosion    689
South Asia                   Bombing/Explosion    131
Southeast Asia               Bombing/Explosion     97
Sub-Saharan Africa           Bombing/Explosion     96
Western Europe               Bombing/Explosion    307
Name: attacktype1_txt, dtype: int64

In [78]:
dfwhole[(dfwhole.attacktype1 ==3) & 
        (dfwhole.iyear == 1994)].groupby(['region_txt']).attacktype1_txt.value_counts()

region_txt                   attacktype1_txt
Australasia & Oceania        Bombing/Explosion      4
Central America & Caribbean  Bombing/Explosion     71
Central Asia                 Bombing/Explosion     26
East Asia                    Bombing/Explosion      6
Eastern Europe               Bombing/Explosion     48
Middle East & North Africa   Bombing/Explosion    292
North America                Bombing/Explosion     19
South America                Bombing/Explosion    180
South Asia                   Bombing/Explosion    135
Southeast Asia               Bombing/Explosion     49
Sub-Saharan Africa           Bombing/Explosion     79
Western Europe               Bombing/Explosion    244
Name: attacktype1_txt, dtype: int64

In [79]:
dfwhole[(dfwhole.attacktype1 ==3) & 
        (dfwhole.iyear == 1995)].groupby(['region_txt']).attacktype1_txt.value_counts()

region_txt                   attacktype1_txt
Australasia & Oceania        Bombing/Explosion      1
Central America & Caribbean  Bombing/Explosion     30
Central Asia                 Bombing/Explosion     13
East Asia                    Bombing/Explosion     11
Eastern Europe               Bombing/Explosion     32
Middle East & North Africa   Bombing/Explosion    176
North America                Bombing/Explosion     17
South America                Bombing/Explosion     82
South Asia                   Bombing/Explosion    175
Southeast Asia               Bombing/Explosion     75
Sub-Saharan Africa           Bombing/Explosion     55
Western Europe               Bombing/Explosion    124
Name: attacktype1_txt, dtype: int64

In [80]:
dfwhole[(dfwhole.attacktype1 ==3) & 
        (dfwhole.iyear == 1996)].groupby(['region_txt']).attacktype1_txt.value_counts()

region_txt                   attacktype1_txt
Australasia & Oceania        Bombing/Explosion      9
Central America & Caribbean  Bombing/Explosion     24
Central Asia                 Bombing/Explosion     15
East Asia                    Bombing/Explosion     63
Eastern Europe               Bombing/Explosion    109
Middle East & North Africa   Bombing/Explosion    157
North America                Bombing/Explosion     19
South America                Bombing/Explosion    165
South Asia                   Bombing/Explosion    251
Southeast Asia               Bombing/Explosion     29
Sub-Saharan Africa           Bombing/Explosion     30
Western Europe               Bombing/Explosion    346
Name: attacktype1_txt, dtype: int64

In [ ]:
dfwhole[(dfwhole.attacktype1 ==3)] & (dfwhole.iyear)